# Special unstaked class for all nodes visible in gossip but without stake
unstaked_class:
  name: solana-unstaked
  fwmark: 1

# Different staked classes, the highest matching class will apply
staked_classes:
  - name: solana-staked
    stake_percentage: 0
    fwmark: 3
  - name: solana-min-staked
    stake_percentage: 0.00003
    fwmark: 5
  - name: solana-high-staked
    stake_percentage: 0.0003
    fwmark: 9

# Custom nodes class, i.e. an allowlist for nodes not in gossip
custom_node_class:
  name: custom-nodes
  fwmark: 7

custom_node_entries:
  - name: snappy
    ip: 192.168.1.1

